# Generated by Django 2.0.3 on 2018-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='atype',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
