# Generated by Django 2.0.3 on 2018-03-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180313_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_type',
            new_name='accountType',
        ),
    ]
